version: "3.8"

services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    command: /bin/bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/spark--org.apache.spark.deploy.master.Master-1-*.out"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
